disable_functions =
max_execution_time = 1000
memory_limit = 1000M
output_buffering = Off
upload_max_filesize = 1000M
post_max_size = 1000M
magic_quotes_gpc = Off
display_errors = Off
open_basedir = Off
allow_url_fopen = On
extension=session
