<?php

namespace Workdo\School\Database\Seeders;

use App\Models\Role;
use App\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Artisan;

class PermissionTableSeeder extends Seeder
{
     public function run()
    {
        Model::unguard();
        Artisan::call('cache:clear');
        $module = 'School';

        $permissions  = [
            'school manage',
            'school_dashboard manage',
            'school_management manage',
            'school_admission manage',
            'school_class manage',
            'school_subject manage',
            'school_timetable manage',
            'school_routinelist manage',
            'school_users manage',
            'school_student manage',
            'school_teacher manage',
            'school_teacher show',
            'school_homework manage',
            'school_admission create',
            'school_admission show',
            'school_admission edit',
            'school_admission delete',
            'school_classroom create',
            'school_classroom manage',
            'school_classroom edit',
            'school_classroom delete',
            'school_subject manage',
            'school_subject create',
            'school_subject edit',
            'school_subject delete',
            'school_timetable manage',
            'school_timetable create',
            'school_timetable edit',
            'school_timetable delete',
            'school_student manage',
            'school_student create',
            'school_student edit',
            'school_student delete',
            'school_student show',
            'school_student bulk upload',
            'school_employee manage',
            'school_employee show',
            'school_employee create',
            'school_employee edit',
            'school_employee delete',
            'school_parent manage',
            'school_parent create',
            'school_parent show',
            'school_parent edit',
            'school_parent delete',
            'school_branch manage',
            'school_branch create',
            'school_branch edit',
            'school_branch delete',
            'school_branch name edit',
            'school_department manage',
            'school_department create',
            'school_department edit',
            'school_department delete',
            'school_department name edit',
            'school_designation manage',
            'school_designation create',
            'school_designation edit',
            'school_designation delete',
            'school_designation name edit',
            'school_homework manage',
            'school_homework create',
            'school_homework edit',
            'school_homework delete',
            'school_teachertimetable manage',
            'school_teachertimetable create',
            'school_teachertimetable edit',
            'school_teachertimetable delete',
            'school_viewhomework manage',
            'school_grade manage',
            'school_grade create',
            'school_grade edit',
            'school_grade delete',
            'school_attendance manage',
            'school_attendance create',
            'school_attendance edit',
            'school_attendance delete',
            'school_bulkattendance manage',
            'school_fee manage',
            'school_fee create',
            'school_fee edit',
            'school_fee delete',
            'school_fee show',
            'school_fees_structure manage',
            'school_fees_structure create',
            'school_fees_structure edit',
            'school_fees_structure delete',
            'library_books manage',
            'library_books create',
            'library_books edit',
            'library_books delete',
            'library_books_issue manage',
            'library_books_issue create',
            'library_books_issue edit',
            'library_books_issue delete',
            'school_bus manage',
            'school_bus create',
            'school_bus edit',
            'school_bus delete',
            'school_transport_route manage',
            'school_transport_route create',
            'school_transport_route edit',
            'school_transport_route delete',
            'school_transport_fees manage',
            'school_transport_fees create',
            'school_transport_fees edit',
            'school_transport_fees delete',
            'school_alumni manage',
            'school_alumni create',
            'school_alumni edit',
            'school_alumni delete',
            'school_event manage',
            'school_event create',
            'school_event edit',
            'school_event delete',
            'school_hostel manage',
            'school_hostel create',
            'school_hostel edit',
            'school_hostel delete',
            'school_room manage',
            'school_room create',
            'school_room edit',
            'school_room delete',
            'school_hostel_student manage',
            'school_hostel_student create',
            'school_hostel_student edit',
            'school_hostel_student delete',
            'school_assessment manage',
            'school_assessment create',
            'school_assessment edit',
            'school_assessment delete',
            'school_assessment_result manage',
            'school_assessment_result create',
            'school_assessment_result edit',
            'school_assessment_result delete',
            'school_notice manage',
            'school_notice create',
            'school_notice edit',
            'school_notice delete',
            'school_health_record manage',
            'school_health_record create',
            'school_health_record edit',
            'school_health_record delete',
            'school_meeting manage',
            'school_meeting create',
            'school_meeting edit',
            'school_meeting delete',
            'school_academic_year manage',
            'school_academic_year create',
            'school_academic_year edit',
            'school_academic_year delete',
            'school_term manage',
            'school_term create',
            'school_term edit',
            'school_term delete',
            'school_assignment manage',
            'school_assignment create',
            'school_assignment edit',
            'school_assignment delete',
            'school_fee_setup manage',
            'school_fee_setup create',
            'school_fee_setup edit',
            'school_fee_setup delete',
            'school_fee_setup show',
            'school_fee_setup generate_invoices',
            'school_fee_setup send_notifications',
            'school_fee_payment manage',
            'school_exam manage',
            'school_exam create',
            'school_exam edit',
            'school_exam delete',
            'school_exam show',
            'school_settings manage',
            'school_exam_entry manage',
            'school_exam_entry create', 
            'school_exam_entry edit',
            'school_exam_entry delete',
            'school_exam_entry show',
            'school_exam_report manage',
            'school_exam_report create',
            'school_exam_report edit',
            'school_exam_report delete',
            'school_exam_report show',
            

            

        ];

        $company_role = Role::where('name','company')->first();
        foreach ($permissions as $key => $value)
        {
            $check = Permission::where('name',$value)->where('module',$module)->exists();
            if($check == false)
            {
                $permission = Permission::create(
                    [
                        'name' => $value,
                        'guard_name' => 'web',
                        'module' => $module,
                        'created_by' => 0,
                        "created_at" => date('Y-m-d H:i:s'),
                        "updated_at" => date('Y-m-d H:i:s')
                    ]
                );
                if(!$company_role->hasPermission($value))
                {
                    $company_role->givePermission($permission);
                }
            }
        }
    }
}
